language: bash

services:
  - docker

jobs:
  include:
    - stage: tests
    - script: find `pwd` -name *.tests.sh | xargs -I {} bash "{}"
    - stage: build
    - script: docker build -t steimntz/editorchecker .
    - stage: deploy
    - script: ./.bin/push
